### ISSUE TITLE
prevent switch from gaining height as width is reduced 

### ISSUE THREAD

**Issue by team-tech-works-uk** [bartbutenaers/node-red-contrib-ui-multistate-switch#7] opened 2021-04-20 12:38 UTC
![image](https://user-images.githubusercontent.com/76047379/115396633-1c535600-a1dd-11eb-8de1-6899b40656ad.png)

the top slider is great .. (60% width of group or larger) .. the lower (60% of group width or less) slider takes 300% more height .. forcing blank spaces everywhere .. ive tried *everything* with a template CSS to over-ride its settings and to get it to behave like other UI elements - but no luck - please advise - thanks

**Comment by bartbutenaers** [comment] 2021-04-20 14:37
Hi @team-tech-works-uk ,
Thanks for reporting this bug!
Unfortunately I cannot develop for a week or 6 from now, due to a surgery.
We will have a look at it afterwards, unless @hotNipi has time meanwhile...
Bart

**Comment by hotNipi** [comment] 2021-04-20 15:10
It is caused by the omitted  height property  from configuration.

**Comment by hotNipi** [comment] 2021-04-20 15:43
That height 0 also restricts to make multiline label available. So creates many problems and should be made available for users to modify. Currently we force but dashboard makes its own magic if width and height match or even for small sizes.

**Comment by team-tech-works-uk** [comment] 2021-04-20 19:49
hotnipi, can you help ? *this is a great/useful UI component* - im using it as a 'better' volume slider plus several other uses.
I have a perhaps 'non-standard' site-setup that allows 'group widths' to be 50 ..
![image](https://user-images.githubusercontent.com/76047379/115454961-43c81400-a219-11eb-88c6-3a63de3e6ec9.png)
which gives much better variation in widget sizes .. perhaps *this* causes the bug ? (like it does with standard sliders which have to be set at 'height=1' or they go mental ..
ANY advice appreciated- *im happy to modify the NODE code for now if needed (I've already modded it to give a sensible 'knob' width for less-wide ms-switch elements) :-) cheers

**Comment by hotNipi** [comment] 2021-04-20 19:56
I pushed fix for size adjustments to the dev branch. If you can checkout the dev branch and try it locally, it would be great help for us too :)
Your site sizes are crazy. But if it all depends what you are doing so they may work. Can say that many dashboard nodes don't support such small unit size.

**Comment by team-tech-works-uk** [comment] 2021-04-23 17:54
@hotNipi - how do i 'use' 'install' .. the 'dev' version? thanks

**Comment by hotNipi** [comment] 2021-04-25 09:39
Oh, I was away from computers ...
If you haven't fount the answer  yet

`npm i bartbutenaers/node-red-contrib-ui-multistate-switch#dev`

**Comment by team-tech-works-uk** [comment] 2021-04-26 15:17
hmm .. thanks for that .. the *best* ive done so far - with that dev code .. is by (header template) setting 
multistate-switch-wrapper - note it mucks up the border - making it 6px high :-) but - for me at the moment - i'll live with that
    {
    height: 6px !important; */
![image](https://user-images.githubusercontent.com/76047379/116106766-51165000-a6aa-11eb-97d6-6e4404db34d7.png)
its weird that my knob-width over-ride (to 8px rather than calculate) WORKS on the lower-slider bu NOT on the upper sliders !!! goodness knows how the various CSS's are being read by the browser to cause this :-)

**Comment by team-tech-works-uk** [comment] 2021-04-30 12:56
any update on this issue wld be appreciated ..

**Comment by bartbutenaers** [comment] 2021-04-30 13:08
See above:

> Unfortunately I cannot develop for a week or 6 from now, due to a surgery.

That is the disadvantage/risc of using open-source...

**Comment by hotNipi** [comment] 2021-04-30 17:29
Based on your last reply, I can't really understand do we still missing something or you are just waiting it to get published.

**Comment by team-tech-works-uk** [comment] 2021-05-03 13:01
as it stands its *better* but NOT sorted .. 
with no css mods its just as bad:
![image](https://user-images.githubusercontent.com/76047379/116866291-0d1fcf80-ac03-11eb-9dc9-bfcf9e6d0847.png)
css mod - better but pretty border mucked up: .multistate-switch-wrapper { height: 6px !important;
![image](https://user-images.githubusercontent.com/76047379/116866056-a7cbde80-ac02-11eb-8709-42e046fb6884.png)
with a bunch of css mods this is the best compromise for my use-case
![image](https://user-images.githubusercontent.com/76047379/116879027-094a7800-ac18-11eb-9ea3-7871634a0cb7.png)

**Comment by team-tech-works-uk** [comment] 2021-05-03 15:49
'pretty much' - actually - *completety* !!  .. a 'nice-to-have' would be a fixed width knob setting to fix this (it dissapears)
![image](https://user-images.githubusercontent.com/76047379/116899533-8e8d5700-ac2f-11eb-9f7c-336277856a6e.png)

**Comment by hotNipi** [comment] 2021-05-03 16:14
I don't see any bulletproof way to width set to something minimum. It brings up too many edge cases ...
But you can definitely override it easily. Just adjust values as you need.
`<style>
.multistate-switch-slider {
    min-width: 16px;
    transform: translateX(-2px);
}
</style>`

**Comment by team-tech-works-uk** [comment] 2021-05-04 22:33
@hotNipi yep thanks .. this turns out to be an incredibly useful ui-component - you've really nailed it - thank you .. here's examples in my use case - happy to share css / flows if of interest:
room-control of CCT leds .. (4-lamps) .. color / brightness / temperature
![image](https://user-images.githubusercontent.com/76047379/117077924-dcd64f00-ad30-11eb-9635-c495ad388e48.png)
non-linear volume-control (max-resolution in mid-range)
![image](https://user-images.githubusercontent.com/76047379/117078043-0e4f1a80-ad31-11eb-802d-10df2f1474ec.png)

**Comment by hotNipi** [comment] 2021-05-05 06:04
any thoughts on allowing 'knob' to be 'dragged' like a standard volume control/fader ??

No I don't think so. It is still switch type of widget. Witch means buttons in row with the indicator of currently selected one. 

I have done once the non-linear (probably was even configurable) slider on top of natural slider component, It is not most easiest thing in the world but still doable.

**Comment by team-tech-works-uk** [comment] 2021-05-05 08:32
ok ta.  The above has been done with *your* MS switch btw :-) (in case that was unclear?) ...

Bug-report? .. When I send MSW a 'value' - it moves to that value _*but doesn't output that value*_ - thoughts? thanks again

**Comment by hotNipi** [comment] 2021-05-05 08:37
Yeah. Take a look at other open issues there is many, talking about pass-through functionality...(not yet supported)

**Comment by team-tech-works-uk** [comment] 2021-05-06 15:25
my tuppence worth .. pass-through wld be the highest priority (and hopefully not too difficult?) cheers again

**Comment by team-tech-works-uk** [comment] 2021-05-10 11:36
@hotNipi .. "pass-through ..." any wild guess at ETA ? is this component still being maintained ? ta

**Comment by bartbutenaers** [comment] 2021-05-10 18:19
> is this component still being maintained ?

If I'm not mistaken I have (twice already) only said the following: *"Unfortunately I cannot develop for a week or 6 from now, due to a surgery."*.  I have no clue where you get the idea this node won't be maintained anymore...

> any wild guess at ETA ?

No ETA's during my free time ...

**Comment by bartbutenaers** [comment] 2021-08-31 22:10
We have now [announced](https://discourse.nodered.org/t/announce-node-red-contrib-ui-multistate-switch-1-2-0-beta/50464) the first beta of version ***1.2.0***, which contains pass through functionality.  I am going to close this issue, since the discussion will be continued on Discourse.

**Closed by bartbutenaers** 2021-08-31 22:10 UTC
